### ISSUE TITLE
[5.0] [RFC] Design for version 5.0

### ISSUE THREAD

**Issue by GrahamCampbell** [DigitalOceanPHP/Client#249]
Lessons learnt from earlier versions:

1. ~Trying to support different versions of Guzzle and Buzz ourselves is a mess, and leads to bugs. We should instead use PSR-7/17/18 with PHP HTTP discovery (replaces #157, #245).~ Done in version 4.0.
2. Entities are a bad idea. They are hard to keep updated and accurate, and frustrating for users. Plain arrays are fine, and the APIs are already documented by DO.
3. Use links for pagination (replaces #7).
4. We need to look over the all the latest APIs and implement them all, but **not spaces** (replaces #232).
5. Builds URI using https://github.com/guzzle/uri-template to avoid errors

**Comment by GrahamCampbell** [comment]
I've just done some work on v3, first, so that migrating from v2 -> v3 shouldn't be too jarring, and then v3 -> v4 will be even simpler. In particular, v3 now automatically discovers the available http clients (either Guzzle or Buzz) in much the same way v4 will. Now you just make a new digital ocean client, and away you go!

**Comment by GrahamCampbell** [comment]
https://github.com/DigitalOceanPHP/Client/tree/3.0#examples

**Comment by glennjacobs** [comment]
Something to consider @GrahamCampbell is that DigitalOcean are creating an OpenAPI spec for their API. This will make generating a PHP client a breeze (if it actually happens). See https://github.com/digitalocean/api-v2/issues/190

I've placed a comment to see what the progress is.

**Comment by bentranter** [comment]
👋 Hey everyone, just wanted to share that we've open sourced our OpenAPI spec at https://github.com/digitalocean/openapi. It's in early access for now and will likely change some more before an official release, but it could be useful to test out client generation, if you're interested 🙂

**Comment by GrahamCampbell** [comment]
Not stale.

**Comment by GrahamCampbell** [comment]
:wave:
